name: emojiscraper

description: >-
  Tiny tool to scrape emoji from https://unicode.org.
  This scrapes emoji-data.txt or emoji-sequences.txt and writes to file/stdout as plaintext/json.

version: 0.2.4

homepage: https://github.com/pjmp/emojiscraper

executables:
  emojiscraper:

environment:
  sdk: ">=2.14.4 <3.0.0"

platforms:
  linux:
  windows:
  macos:

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.1
  test: ^1.19.3

dependencies:
  args: ^2.3.0
  build: ^2.2.1
  html: ^0.15.0
  interact: ^2.1.1
  logging: ^1.0.2
  yaml: ^3.1.0
