name: emojiscraper
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/pjmp/emojiscraper

executables:
  emojiscraper:

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3

dependencies: 
  html: ^0.15.0
  args: ^2.3.0
  yaml: ^3.1.0
  interact: ^2.1.1
  logging: ^1.0.2
  build_runner: ^2.1.5
